######################################################
# Allen Visual Behavior Neuropixels (2019) 
######################################################

DATASET = "allen_visual_behavior_neuropixels"

RAW_DIR = config["RAW_DIR"]
PROCESSED_DIR = config["PROCESSED_DIR"]
COMPRESSED_DIR = config["COMPRESSED_DIR"]

SESSION_IDS = [
    "715093703", "719161530", "721123822", "732592105", "737581020", "739448407", 
    "742951821", "743475441", "744228101", "746083955", "750332458", "750749662", 
    "751348571", "754312389", "754829445", "755434585", "756029989", "757216464", 
    "757970808", "758798717", "759883607", "760345702", "760693773", "761418226", 
    "762120172", "762602078", "763673393", "766640955", "767871931", "768515987", 
    "771160300", "771990200", "773418906", "774875821", "778240327", "778998620", 
    "779839471", "781842082", "786091066", "787025148", "789848216", "791319847",
    "793224716", "794812542", "797828357", "798911424", "799864342", "816200189", 
    "819186360", "819701982", "821695405", "829720705", "831882777", "835479236", 
    "839068429", "839557629", "840012044", "847657808", 
]

rule all:
    input:
        f"{PROCESSED_DIR}/{DATASET}/description.mpk"

rule download_one:
    output:
        nwb_file = f"{RAW_DIR}/{DATASET}/session_{{session_id}}/session_{{session_id_}}.nwb"
    shell:
        f"""
        mkdir -p {RAW_DIR}/{DATASET}
        python data/scripts/{DATASET}/download_data.py --output_dir {RAW_DIR}/{DATASET} --session_id {{wildcards.session_id}}
        """

rule download_all:
    input:
        nwb_files = expand(f"{RAW_DIR}/{DATASET}/session_{{dataset}}/session_{{dataset}}.nwb", dataset=SESSION_IDS)

rule prepare_data:
    input:
        py_script = f"data/scripts/{DATASET}/prepare_data.py",
        nwb_files = expand(f"{RAW_DIR}/{DATASET}/session_{{dataset}}/session_{{dataset}}.nwb", dataset=SESSION_IDS)
    output:
        description = f"{PROCESSED_DIR}/{DATASET}/description.mpk"
    shell:
        f"""
        mkdir -p {PROCESSED_DIR}/{DATASET}
        python data/scripts/{DATASET}/prepare_data.py --input_dir {RAW_DIR}/{DATASET} --output_dir {PROCESSED_DIR}/{DATASET}
        """

include: "../freeze.smk"