_target_: kirby.models.CaPOYO
dim: 128
dim_input: 64
dim_head: 64
patch_size: 1
num_latents: 16
depth: 6
cross_heads: 2
self_heads: 8
ffn_dropout: 0.2
lin_dropout: 0.4
atn_dropout: 0.2
use_cre_line_embedding: True
use_depth_embedding: True