- selection:
    - dandiset: d23a44ef-1402-4ed7-97f5-47e9a7a504d9_aligned
      sortsets:
      - d23a44ef-1402-4ed7-97f5-47e9a7a504d9
  config:
    multitask_readout:
      - decoder_id: WHEEL
        metrics:
          - metric: r2
        normalize_mean:
          - 0.5911670327186584
        normalize_std:
          - 1.0917785315431314

