- selection:
    - dandiset: d23a44ef-1402-4ed7-97f5-47e9a7a504d9_aligned
      sortsets:
      - d23a44ef-1402-4ed7-97f5-47e9a7a504d9
- config:
    multitask_readout:
      - decoder_id: WHISKER
        metrics:
        - metric: r2
        normalize_mean:
        - 3.745565554515258
        normalize_std:
        - 3.1527659072008927
