- selection:
    - dandiset: "d23a44ef-1402-4ed7-97f5-47e9a7a504d9_unaligned"
      sortsets:
      - d23a44ef-1402-4ed7-97f5-47e9a7a504d9
  config:
    multitask_readout:
      - decoder_id: WHISKER
        normalize_mean:
          - 3.75224020
        normalize_std:
          - 3.47473943
        metrics:
          - metric: r2
