#######################################################################
# Bouchard & Chang Human ECoG speaking consonant-vowel syllables (2019) 
#######################################################################

DATASET = "bouchard_chang"

RAW_DIR = config["RAW_DIR"]
PROCESSED_DIR = config["PROCESSED_DIR"]

SESSION_IDS = [
    "sub-EC2_ses-EC2-B8", "sub-EC2_ses-EC2-B9", "sub-EC2_ses-EC2-B15", "sub-EC2_ses-EC2-B76", 
    "sub-EC2_ses-EC2-B89", "sub-EC2_ses-EC2-B105", "sub-EC9_ses-EC9-B15", "sub-EC9_ses-EC9-B39",
    "sub-EC9_ses-EC9-B46", "sub-EC9_ses-EC9-B49", "sub-EC9_ses-EC9-B53", "sub-EC9_ses-EC9-B60",
    "sub-EC9_ses-EC9-B63", "sub-GP31_ses-GP31-B1", "sub-GP31_ses-GP31-B2", "sub-GP31_ses-GP31-B4",
    "sub-GP31_ses-GP31-B6", "sub-GP31_ses-GP31-B9", "sub-GP31_ses-GP31-B21", "sub-GP31_ses-GP31-B63",
    "sub-GP31_ses-GP31-B65", "sub-GP31_ses-GP31-B67", "sub-GP31_ses-GP31-B69", "sub-GP31_ses-GP31-B71",
    "sub-GP31_ses-GP31-B78", "sub-GP31_ses-GP31-B82", "sub-GP31_ses-GP31-B83", "sub-GP33_ses-GP33-B1",
    "sub-GP33_ses-GP33-B5", "sub-GP33_ses-GP33-B30",
]

FOLDER_IDS = [session_str.split('_')[0] for session_str in SESSION_IDS]

rule all:
    input:
        f"{PROCESSED_DIR}/{DATASET}/description.mpk"

rule prepare_data:
    input:
        py_script = f"data/scripts/{DATASET}/prepare_data.py",
        nwb_files = expand(f"{RAW_DIR}/{DATASET}/{{folder}}/{{dataset}}.nwb", zip, folder=FOLDER_IDS, dataset=SESSION_IDS)
    output:
        description = f"{PROCESSED_DIR}/{DATASET}/description.mpk"
    shell:
        f"""
        mkdir -p {PROCESSED_DIR}/{DATASET}
        python data/scripts/{DATASET}/prepare_data.py --input_dir {RAW_DIR}/{DATASET} --output_dir {PROCESSED_DIR}/{DATASET}
        """

include: "../freeze.smk"
