######################################################
# Openscope dataset - Gillon & Richards (2023)
######################################################

DATASET = "gillon_richards_responses_2023"
DANDI_ID = "000037"

RAW_DIR = config["RAW_DIR"]
PROCESSED_DIR = config["PROCESSED_DIR"]
COMPRESSED_DIR = config["COMPRESSED_DIR"]

DATASETS = [
    "sub-408021_ses-758519303",
    "sub-408021_ses-759189643",
    "sub-408021_ses-759660390",
    "sub-411400_ses-759666166",
    "sub-411400_ses-759872185",
    "sub-411400_ses-760269100",
    "sub-411400_ses-761730740",
    "sub-411400_ses-762415169",
    "sub-411400_ses-763646681",
    "sub-411424_ses-761624763",
    "sub-411424_ses-761944562",
    "sub-411424_ses-762250376",
    "sub-411771_ses-760260459",
    "sub-411771_ses-760659782",
    "sub-411771_ses-761269197",
    "sub-412933_ses-763949859",
    "sub-412933_ses-764897534",
    "sub-412933_ses-765427689",
    "sub-412933_ses-766755831",
    "sub-412933_ses-767254594",
    "sub-412933_ses-768807532",
    "sub-413663_ses-764704289",
    "sub-413663_ses-765193831",
    "sub-413663_ses-766502238",
    "sub-418779_ses-777496949",
    "sub-418779_ses-778374308",
    "sub-418779_ses-779152062",
    "sub-420011_ses-777914830",
    "sub-420011_ses-778864809",
    "sub-420011_ses-779650018",
    "sub-433414_ses-826187862",
    "sub-433414_ses-826773996",
    "sub-433414_ses-827833392",
    "sub-433448_ses-826338612",
    "sub-433448_ses-826819032",
    "sub-433448_ses-828816509",
    "sub-433448_ses-829283315",
    "sub-433451_ses-823453391",
    "sub-433451_ses-824434038",
    "sub-433451_ses-825180479",
    "sub-433458_ses-826659257",
    "sub-433458_ses-827300090",
    "sub-433458_ses-828475005",
    "sub-433458_ses-829520904",
    "sub-440889_ses-832883243",
    "sub-440889_ses-833704570",
    "sub-440889_ses-834403597",
    "sub-440889_ses-836968429",
    "sub-440889_ses-837360280",
    "sub-440889_ses-838633305",
    ]

rule all:
    input:
        f"{PROCESSED_DIR}/{DATASET}/description.mpk"

#rule download_dataset:
#    output:
#        nwb_files = expand(f"{RAW_DIR}/{DATASET}/{{dataset}}_behavior+ophys.nwb", dataset=DATASETS)
#   shell:
#        f"""
#        mkdir -p {RAW_DIR}/{DATASET}
#
#        yaml_output=$(dandi ls -r DANDI:000037/0.240209.1623)    
#        asset_ids=$(echo "$yaml_output" | yq -r '.[] | select(.path | endswith("_behavior+ophys.nwb")) | .asset_id')

#        while IFS= read -r asset_id; do
#           dandi download -o {RAW_DIR}/{DATASET} "https://api.dandiarchive.org/api/dandisets/000037/versions/0.240209.1623/assets/$asset_id/download/"
#        done <<< "$asset_ids"
#        """

rule prepare_data:
    input:
        py_script = f"data/scripts/{DATASET}/prepare_data.py",
        nwb_files = expand(f"{RAW_DIR}/{DATASET}/{{dataset}}_behavior+ophys.nwb", dataset=DATASETS)
    output:
        description = f"{PROCESSED_DIR}/{DATASET}/description.mpk"
    log:
        f".snakemake/logs/{DATASET}/prepare_data.log"
    shell:
        f"""
        pip install -r data/scripts/{DATASET}/requirements.txt
        mkdir -p {PROCESSED_DIR}/{DATASET}
        python data/scripts/{DATASET}/prepare_data.py --input_dir {RAW_DIR}/{DATASET} --output_dir {PROCESSED_DIR}/{DATASET}
        """

include: "../freeze.smk"
