######################################################
# Yu & Smith (2022) - Calcium v1al from Neuroformer
######################################################

DATASET = "yu_smith_selective_2022"

RAW_DIR = config["RAW_DIR"]
PROCESSED_DIR = config["PROCESSED_DIR"]


rule all:
    input:
        f"{PROCESSED_DIR}/{DATASET}/description.mpk"


rule download_data:
    output:
        nwb_file = f"{RAW_DIR}/{DATASET}/Combo3_AL.mat"
    shell:
        f"""
        echo "Data cannot be downloaded automatically. Please ask Mehdi for the data."
        echo "This is temporary, and we will host the raw data somewhere."
        exit 1
        """

rule prepare_data:
    input:
        py_script = f"data/scripts/{DATASET}/prepare_data.py",
        nwb_file = f"{RAW_DIR}/{DATASET}/Combo3_AL.mat"
    output:
        description = f"{PROCESSED_DIR}/{DATASET}/description.mpk"
    log:
        f".snakemake/logs/{DATASET}/prepare_data.log"
    shell:
        f"""
        mkdir -p {PROCESSED_DIR}/{DATASET}
        python data/scripts/{DATASET}/prepare_data.py --input_dir {RAW_DIR}/{DATASET} --output_dir {PROCESSED_DIR}/{DATASET}
        """

include: "../freeze.smk"
