######################################################
# Even-Chen et al. (2019)
######################################################

DATASET = "evenchen_shenoy_structure_2019"
DANDI_ID = "000121"
DANDI_VERSION = "0.220124.2156"

DATASETS = [
    "sub-JenkinsC/sub-JenkinsC_ses-20151001T150307",
    "sub-JenkinsC/sub-JenkinsC_ses-20151002T143706",
    "sub-JenkinsC/sub-JenkinsC_ses-20151015T151424",
    "sub-JenkinsC/sub-JenkinsC_ses-20160127T110630",
    "sub-JenkinsC/sub-JenkinsC_ses-20160128T160749",
    "sub-Reggie/sub-Reggie_ses-20170115T125333",
    "sub-Reggie/sub-Reggie_ses-20170116T102856",
    "sub-Reggie/sub-Reggie_ses-20170117T104643",
    "sub-Reggie/sub-Reggie_ses-20170118T094022",
    "sub-Reggie/sub-Reggie_ses-20170119T123128",
    "sub-Reggie/sub-Reggie_ses-20170124T094957",
    "sub-Reggie/sub-Reggie_ses-20170125T100800",
]

RAW_DIR = config["RAW_DIR"]
PROCESSED_DIR = config["PROCESSED_DIR"]

rule all:
    input:
        f"{PROCESSED_DIR}/{DATASET}/description.mpk"

rule download_dataset:
    output:
        nwb_files = expand(f"{RAW_DIR}/{DATASET}/{DANDI_ID}/{{dataset}}_behavior+ecephys.nwb", dataset=DATASETS)
    shell:
        f"""
        mkdir -p {RAW_DIR}/{DATASET}
        dandi download -o {RAW_DIR}/{DATASET} -e refresh DANDI:{DANDI_ID}/{DANDI_VERSION}
        """

rule prepare_data:
    input:
        py_script = f"data/scripts/{DATASET}/prepare_data.py",
        nwb_files = expand(f"{RAW_DIR}/{DATASET}/{DANDI_ID}/{{dataset}}_behavior+ecephys.nwb", dataset=DATASETS)
    output:
        description = f"{PROCESSED_DIR}/{DATASET}/description.mpk"
    shell:
        f"""
        mkdir -p {PROCESSED_DIR}/{DATASET}
        python data/scripts/{DATASET}/prepare_data.py --input_dir {RAW_DIR}/{DATASET} --output_dir {PROCESSED_DIR}/{DATASET}
        """

include: "../freeze.smk"
