- selection:
    - dandiset: "ibl"
      sortsets:
      - c7bf2d49-4937-4597-b307-9f39cb1c7b16
  config:
    multitask_readout:
      - decoder_id: CHOICE
        metrics:
          - metric: accuracy
      - decoder_id: BLOCK
        metrics:
          - metric: accuracy
      - decoder_id: WHEEL
        normalize_mean:
          - 1.04661810
        normalize_std:
          - 1.13883926
        metrics:
          - metric: r2
      - decoder_id: WHISKER
        normalize_mean:
          - 5.71447079
        normalize_std:
          - 2.88609730
        metrics:
          - metric: r2
