- selection:
    - dandiset: "d23a44ef-1402-4ed7-97f5-47e9a7a504d9_aligned"
      sortsets:
      - d23a44ef-1402-4ed7-97f5-47e9a7a504d9
  config:
    multitask_readout:
      - decoder_id: CHOICE
        metrics:
          - metric: accuracy
