- config:
    multitask_readout:
    - decoder_id: WHEEL
      metrics:
      - metric: r2
      normalize_mean:
      - 0.5255402749970725
      normalize_std:
      - 0.9540522263241659
    - decoder_id: WHISKER
      metrics:
      - metric: r2
      normalize_mean:
      - 7.038940894749956
      normalize_std:
      - 4.949504295261157
    - decoder_id: BLOCK
      metrics:
      - metric: accuracy
    - decoder_id: CHOICE
      metrics:
      - metric: accuracy
  selection:
  - dandiset: ibl_d0ea3148-948d-4817-94f8-dcaf2342bbbe
    sortsets:
    - d0ea3148-948d-4817-94f8-dcaf2342bbbe
- config:
    multitask_readout:
    - decoder_id: WHEEL
      metrics:
      - metric: r2
      normalize_mean:
      - 0.5255402749970725
      normalize_std:
      - 0.9540522263241659
    - decoder_id: WHISKER
      metrics:
      - metric: r2
      normalize_mean:
      - 7.038940894749956
      normalize_std:
      - 4.949504295261157
    - decoder_id: BLOCK
      metrics:
      - metric: accuracy
    - decoder_id: CHOICE
      metrics:
      - metric: accuracy
  selection:
  - dandiset: ibl_3638d102-e8b6-4230-8742-e548cd87a949
    sortsets:
    - 3638d102-e8b6-4230-8742-e548cd87a949
- config:
    multitask_readout:
    - decoder_id: WHEEL
      metrics:
      - metric: r2
      normalize_mean:
      - 0.5255402749970725
      normalize_std:
      - 0.9540522263241659
    - decoder_id: WHISKER
      metrics:
      - metric: r2
      normalize_mean:
      - 7.038940894749956
      normalize_std:
      - 4.949504295261157
    - decoder_id: BLOCK
      metrics:
      - metric: accuracy
    - decoder_id: CHOICE
      metrics:
      - metric: accuracy
  selection:
  - dandiset: ibl_41872d7f-75cb-4445-bb1a-132b354c44f0
    sortsets:
    - 41872d7f-75cb-4445-bb1a-132b354c44f0
- config:
    multitask_readout:
    - decoder_id: WHEEL
      metrics:
      - metric: r2
      normalize_mean:
      - 0.5255402749970725
      normalize_std:
      - 0.9540522263241659
    - decoder_id: WHISKER
      metrics:
      - metric: r2
      normalize_mean:
      - 7.038940894749956
      normalize_std:
      - 4.949504295261157
    - decoder_id: BLOCK
      metrics:
      - metric: accuracy
    - decoder_id: CHOICE
      metrics:
      - metric: accuracy
  selection:
  - dandiset: ibl_db4df448-e449-4a6f-a0e7-288711e7a75a
    sortsets:
    - db4df448-e449-4a6f-a0e7-288711e7a75a
- config:
    multitask_readout:
    - decoder_id: WHEEL
      metrics:
      - metric: r2
      normalize_mean:
      - 0.5255402749970725
      normalize_std:
      - 0.9540522263241659
    - decoder_id: WHISKER
      metrics:
      - metric: r2
      normalize_mean:
      - 7.038940894749956
      normalize_std:
      - 4.949504295261157
    - decoder_id: BLOCK
      metrics:
      - metric: accuracy
    - decoder_id: CHOICE
      metrics:
      - metric: accuracy
  selection:
  - dandiset: ibl_dac3a4c1-b666-4de0-87e8-8c514483cacf
    sortsets:
    - dac3a4c1-b666-4de0-87e8-8c514483cacf
- config:
    multitask_readout:
    - decoder_id: WHEEL
      metrics:
      - metric: r2
      normalize_mean:
      - 0.5255402749970725
      normalize_std:
      - 0.9540522263241659
    - decoder_id: WHISKER
      metrics:
      - metric: r2
      normalize_mean:
      - 7.038940894749956
      normalize_std:
      - 4.949504295261157
    - decoder_id: BLOCK
      metrics:
      - metric: accuracy
    - decoder_id: CHOICE
      metrics:
      - metric: accuracy
  selection:
  - dandiset: ibl_ecb5520d-1358-434c-95ec-93687ecd1396
    sortsets:
    - ecb5520d-1358-434c-95ec-93687ecd1396
- config:
    multitask_readout:
    - decoder_id: WHEEL
      metrics:
      - metric: r2
      normalize_mean:
      - 0.5255402749970725
      normalize_std:
      - 0.9540522263241659
    - decoder_id: WHISKER
      metrics:
      - metric: r2
      normalize_mean:
      - 7.038940894749956
      normalize_std:
      - 4.949504295261157
    - decoder_id: BLOCK
      metrics:
      - metric: accuracy
    - decoder_id: CHOICE
      metrics:
      - metric: accuracy
  selection:
  - dandiset: ibl_f312aaec-3b6f-44b3-86b4-3a0c119c0438
    sortsets:
    - f312aaec-3b6f-44b3-86b4-3a0c119c0438
- config:
    multitask_readout:
    - decoder_id: WHEEL
      metrics:
      - metric: r2
      normalize_mean:
      - 0.5255402749970725
      normalize_std:
      - 0.9540522263241659
    - decoder_id: WHISKER
      metrics:
      - metric: r2
      normalize_mean:
      - 7.038940894749956
      normalize_std:
      - 4.949504295261157
    - decoder_id: BLOCK
      metrics:
      - metric: accuracy
    - decoder_id: CHOICE
      metrics:
      - metric: accuracy
  selection:
  - dandiset: ibl_4b7fbad4-f6de-43b4-9b15-c7c7ef44db4b
    sortsets:
    - 4b7fbad4-f6de-43b4-9b15-c7c7ef44db4b
- config:
    multitask_readout:
    - decoder_id: WHEEL
      metrics:
      - metric: r2
      normalize_mean:
      - 0.5255402749970725
      normalize_std:
      - 0.9540522263241659
    - decoder_id: WHISKER
      metrics:
      - metric: r2
      normalize_mean:
      - 7.038940894749956
      normalize_std:
      - 4.949504295261157
    - decoder_id: BLOCK
      metrics:
      - metric: accuracy
    - decoder_id: CHOICE
      metrics:
      - metric: accuracy
  selection:
  - dandiset: ibl_30c4e2ab-dffc-499d-aae4-e51d6b3218c2
    sortsets:
    - 30c4e2ab-dffc-499d-aae4-e51d6b3218c2
- config:
    multitask_readout:
    - decoder_id: WHEEL
      metrics:
      - metric: r2
      normalize_mean:
      - 0.5255402749970725
      normalize_std:
      - 0.9540522263241659
    - decoder_id: WHISKER
      metrics:
      - metric: r2
      normalize_mean:
      - 7.038940894749956
      normalize_std:
      - 4.949504295261157
    - decoder_id: BLOCK
      metrics:
      - metric: accuracy
    - decoder_id: CHOICE
      metrics:
      - metric: accuracy
  selection:
  - dandiset: ibl_781b35fd-e1f0-4d14-b2bb-95b7263082bb
    sortsets:
    - 781b35fd-e1f0-4d14-b2bb-95b7263082bb
