- selection:
    - dandiset: "allen_visual_behavior_neuropixels"
      sortsets:
      - mouse_699733581_20190119
  config:
    multitask_readout:
      - decoder_id: GABOR_POS_2D
        metrics:
          - metric: r2
      - decoder_id: GABOR_ORIENTATION
        metrics:
          - metric: accuracy
      - decoder_id: DRIFTING_GRATINGS
        metrics:
          - metric: accuracy
      - decoder_id: DRIFTING_GRATINGS_TEMP_FREQ
        metrics:
          - metric: accuracy
      - decoder_id: RUNNING_SPEED
        metrics:
          - metric: r2
      - decoder_id: STATIC_GRATINGS
        metrics:
          - metric: accuracy