- selection:
    - dandiset: "ibl"
      sortsets:
      - c7bf2d49-4937-4597-b307-9f39cb1c7b16
  config:
    multitask_readout:
      - decoder_id: WHISKER
        normalize_mean:
          - 5.38157386
        normalize_std:
          - 2.64732626
        metrics:
          - metric: r2
