######################################################
# Perich & Miller (2018) 
######################################################

DATASET = "perich_miller_population_2018"
DANDI_ID = "000688"
# use one file to check if data is downloaded
FILENAME = "sub-T/sub-T_ses-RT-20130910_behavior+ecephys.nwb"

RAW_DIR = config["RAW_DIR"]
PROCESSED_DIR = config["PROCESSED_DIR"]

rule all:
    input:
        f"{PROCESSED_DIR}/{DATASET}/description.mpk"

rule download_data:
    output:
        nwb_file = f"{RAW_DIR}/{DATASET}/{DANDI_ID}/{FILENAME}"
    shell:
        f"""
        mkdir -p {RAW_DIR}/{DATASET}
        dandi download -o {RAW_DIR}/{DATASET} -e refresh DANDI:000688/draft
        """

rule prepare_data:
    input:
        py_script = f"data/scripts/{DATASET}/prepare_data.py",
        nwb_file = f"{RAW_DIR}/{DATASET}/{DANDI_ID}/{FILENAME}"
    output:
        description = f"{PROCESSED_DIR}/{DATASET}/description.mpk"
    log:
        f".snakemake/logs/{DATASET}/prepare_data.log"
    shell:
        f"""
        mkdir -p {PROCESSED_DIR}/{DATASET}
        python data/scripts/{DATASET}/prepare_data.py --input_dir {RAW_DIR}/{DATASET} --output_dir {PROCESSED_DIR}/{DATASET}
        """

include: "../freeze.smk"
