# Path: configs/train.yaml
defaults:
  - _self_
  - model: capoyo1.3M_3.yaml
  - dataset: allen_brain_observatory_calcium_model1_wildtype.yaml

train_transforms:
  - _target_: kirby.transforms.UnitDropout
    field: "calcium_traces.df_over_f"
    min_units: 10
    mode_units: 50
    max_units: 300
    tail_right: 100
    peak: 50
    M: 50

data_root: ${oc.env:SLURM_TMPDIR}/uncompressed
seed: 42
batch_size: 128
eval_epochs: 1
use_sparse_lamb: True
steps: 0  # Note we either specify epochs or steps, not both.
epochs: 1000
base_lr: 1.5625e-5
weight_decay: 0.0001
# Fraction of epochs to warmup for.
pct_start: 0.5
num_workers: 4
log_dir: ./logs
name: model3_wildtype
precision: 32
nodes: 1
gpus: 1
patch_size: 1
# Where to resume/finetune from. Could be null (yaml for None, meaning train from
# scratch) or a fully qualified path to the .ckpt file.
ckpt_path: null

# Finetuning configuration:
finetune: false
# Num of epochs to freeze perceiver network while finetuning
# -1 => Keep frozen, i.e. perform Unit-identification
#  0 => Train everything
# >0 => Only train unit/session embeddings for first few epochs,
#       and then train everything
freeze_perceiver_until_epoch: 0
