# Path: configs/train.yaml
defaults:
  - _self_
  - model: capoyo1.3M.yaml
  - dataset: gillon_richards_responses_2023.yaml

train_transforms:
  - _target_: kirby.transforms.UnitDropout
    field: "calcium_traces.df_over_f"
    max_units: 1000
    min_units: 20
    mode_units: 60
    peak: 4

data_root: ./data/uncompressed/
seed: 42
batch_size: 128
eval_epochs: 10
steps: 0  # Note we either specify epochs or steps, not both.
epochs: 500
base_lr: 1.5625e-5
weight_decay: 1e-4
# Fraction of epochs to warmup for.
pct_start: 0.5
num_workers: 4
log_dir: ./logs
name: calcium_openscope_single_sess_all
backend_config: gpu_fp32
precision: 32
nodes: 1
gpus: 1
# Where to resume/finetune from. Could be null (yaml for None, meaning train from
# scratch) or a fully qualified path to the .ckpt file.
ckpt_path: null

# Finetuning configuration:
finetune: false
# Num of epochs to freeze perceiver network while finetuning
# -1 => Keep frozen, i.e. perform Unit-identification
#  0 => Train everything
# >0 => Only train unit/session embeddings for first few epochs,
#       and then train everything
freeze_perceiver_until_epoch: 0
