#######################################################################
# Orsborn Lab UW ECoG motor reaching dataset  
#######################################################################

DATASET = "orsborn_lab_ecog_reaching_2024"

RAW_DIR = config["RAW_DIR"]
PROCESSED_DIR = config["PROCESSED_DIR"]

SUBJECT_IDS = [
    "beignet_2022-06-28_2022-06-29_kinematics_and_lfp", "affi_2024-01-02_2024-01-04_kinematics_and_lfp",
]

rule all:
    input:
        f"{PROCESSED_DIR}/{DATASET}/description.mpk"

rule prepare_data:
    input:
        py_script = f"data/scripts/{DATASET}/prepare_data.py",
        nwb_files = expand(f"{RAW_DIR}/{DATASET}/{{dataset}}.pkl", dataset=SUBJECT_IDS)
    output:
        description = f"{PROCESSED_DIR}/{DATASET}/description.mpk"
    shell:
        f"""
        mkdir -p {PROCESSED_DIR}/{DATASET}
        python data/scripts/{DATASET}/prepare_data.py --input_dir {RAW_DIR}/{DATASET} --output_dir {PROCESSED_DIR}/{DATASET}
        """

include: "../freeze.smk"
