- selection:
    - dandiset: "allen_brain_observatory_calcium"
      sortsets: 
        - "617381605"
        - "623587006"
        - "637669270"
        - "637671554"
        - "643645390"
        - "657016267"
        - "657391625"
  config:
    sampling_intervals_modifier: |
      sampling_intervals = sampling_intervals & data.drifting_gratings
      if split == "train":
        sampling_intervals = sampling_intervals.dilate(0.5, max_len=2.0)
      else:
        sampling_intervals = sampling_intervals.dilate(0.5, max_len=2.0)
    multitask_readout:
      - decoder_id: DRIFTING_GRATINGS
        metrics:
          - metric: accuracy