- selection:
    - dandiset: "allen_natural_movie_calcium"

  config:
    sampling_intervals_modifier: |
      sampling_intervals = sampling_intervals & data.natural_movie_one_epochs
    multitask_readout:
      - decoder_id: NATURAL_MOVIE_FRAME
        #normalize_mean:
        #  - 450.0
        #normalize_std:
        #  - 450.0
        metrics:
          - metric: accuracy
          - metric: frame_diff_acc