- selection:
    - dandiset: "allen_brain_observatory_calcium"
      sortsets: 
        - "603576132"
        - "604145810"
        - "604529230"
        - "605883133"
        - "627823695"
        - "637126541"
        - "645086975"
        - "647143225"
        - "647595671"
        - "665722301"
        - "665726618"
        - "667004159"
        - "669237515"
        - "669859475"
        - "670395725"
        - "698762886"
  config:
    sampling_intervals_modifier: |
      sampling_intervals = sampling_intervals & data.drifting_gratings
      if split == "train":
        sampling_intervals = sampling_intervals.dilate(0.5, max_len=2.0)
      else:
        sampling_intervals = sampling_intervals.dilate(0.5, max_len=2.0)
    multitask_readout:
      - decoder_id: DRIFTING_GRATINGS
        metrics:
          - metric: accuracy