- selection:
    - dandiset: "allen_brain_observatory_calcium"
      exclude_sortsets: 
        - "510514474"
        - "512326618"
        - "560926639"
        - "595806300"
        - "562122508"
        - "623347352"
        - "652737678"
        - "555042467"
        - "539487468"
        - "710504563"
        - "676503588"
        - "671164733"
        - "649401936"
        - "595273803"
        - "654532828"
        - "505695962"
        - "539497234"
        - "547388708"
        - "646016204"
        - "637669284"
        - "653122667"
        - "623339221"
        - "589441079"
        - "603763073"
        - "649938038"
        - "645689073"
        - "652092676"
        - "649409874"
        - "669233895"
        - "689388034"
  config:
    sampling_intervals_modifier: |
      if split == "train":
        sampling_intervals = sampling_intervals & (data.drifting_gratings | data.natural_movie_one_epochs)
        sampling_intervals = sampling_intervals.dilate(0.5, max_len=2.0)
      else:
        sampling_intervals = sampling_intervals & data.drifting_gratings
        sampling_intervals = sampling_intervals.dilate(0.5, max_len=2.0)
    multitask_readout:
      - decoder_id: DRIFTING_GRATINGS
        weight: 5.0
        metrics:
          - metric: accuracy
      - decoder_id: DRIFTING_GRATINGS_TEMP_FREQ
        metrics:
          - metric: accuracy
      - decoder_id: NATURAL_MOVIE_FRAME
        metrics:
          - metric: frame_diff_acc