##### BRAIN OBERVATORY 1.1 SESSIONS ####
# these sessions have all
- selection:
    - dandiset: "allen_visual_behavior_neuropixels"
      sortsets:
      - mouse_723627604_20181026
      - mouse_722882755_20181026
      - mouse_719817805_20180925
      - mouse_726170935_20181026
      - mouse_726141251_20180925
      - mouse_726162197_20181026
      - mouse_732548380_20180925
      - mouse_719828690_20180925
      - mouse_726298253_20181026
      - mouse_730760270_20181026
      - mouse_734865738_20181026
      - mouse_733457989_20181026
      - mouse_730756780_20181026
      - mouse_735109609_20181031
      - mouse_740268986_20181026
      - mouse_739783171_20190119
      - mouse_738651054_20181026
      - mouse_742714475_20181026
      - mouse_745276236_20181026
      - mouse_744915204_20181026
      - mouse_742602892_20181206
      - mouse_757329624_20181210
      - mouse_769360779_20190108
      - mouse_776061251_20190108
      - mouse_775876828_20181221
      - mouse_772616823_20190108
  config:
    multitask_readout:
      - decoder_id: GABOR_POS_2D
        normalize_mean:
          - 4.00198751
          - 3.99451069
        normalize_std:
          - 2.58303208
          - 2.57868835
        metrics:
          - metric: r2
      - decoder_id: GABOR_ORIENTATION
        metrics:
          - metric: accuracy
      - decoder_id: DRIFTING_GRATINGS
        metrics:
          - metric: accuracy
      - decoder_id: DRIFTING_GRATINGS_TEMP_FREQ
        metrics:
          - metric: accuracy
      - decoder_id: RUNNING_SPEED
        normalize_mean: 10.97099596
        normalize_std: 19.75150106
        metrics:
          - metric: r2
      - decoder_id: GAZE_POS_2D
        normalize_mean:
          - 4.89581651
          - -1.97602398
        normalize_std:
          - 1.26124560
          - 1.19413048
        metrics:
          - metric: r2
      - decoder_id: PUPIL_SIZE_2D
        normalize_mean:
          - 43.09496815
          - 46.94002598
        normalize_std:
          - 13.91880302
          - 15.23047149
        metrics:
          - metric: r2
      - decoder_id: STATIC_GRATINGS
        metrics:
          - metric: accuracy
      - decoder_id: NATURAL_SCENES
        metrics:
          - metric: accuracy

# these sessions have only ('drifting_gratings', 'gabors', 'static_gratings', 'velocity')
# i.e, missing gaze and pupil info
- selection:
    - dandiset: "allen_visual_behavior_neuropixels"
      sortsets:
      - mouse_699733581_20190119
      - mouse_703279284_20190108
      - mouse_707296982_20190108
      - mouse_717038288_20190108
      - mouse_718643567_20180925
      - mouse_716813543_20190108
  config:
    multitask_readout:
      - decoder_id: GABOR_POS_2D
        normalize_mean:
          - 4.00198751
          - 3.99451069
        normalize_std:
          - 2.58303208
          - 2.57868835
        metrics:
          - metric: r2
      - decoder_id: GABOR_ORIENTATION
        metrics:
          - metric: accuracy
      - decoder_id: DRIFTING_GRATINGS
        metrics:
          - metric: accuracy
      - decoder_id: DRIFTING_GRATINGS_TEMP_FREQ
        metrics:
          - metric: accuracy
      - decoder_id: RUNNING_SPEED
        normalize_mean: 10.97099596
        normalize_std: 19.75150106
        metrics:
          - metric: r2
      - decoder_id: STATIC_GRATINGS
        metrics:
          - metric: accuracy
      - decoder_id: NATURAL_SCENES
        metrics:
          - metric: accuracy


##### FUNCTIONAL CONNECTIVITY SESSIONS ######

# these sessions have only ('drifting_gratings', 'gabors', 'gaze', 'pupil', 'velocity')
# i.e missing static_gratings info
- selection:
    - dandiset: "allen_visual_behavior_neuropixels"
      sortsets:
      - mouse_744912849_20190102
      - mouse_753795610_20190102
      - mouse_754488979_20181105
      - mouse_756578435_20181105
      - mouse_759711152_20181210
      - mouse_760938797_20181210
      - mouse_759674770_20181210
      - mouse_760960653_20181210
      - mouse_760946813_20181210
      - mouse_763884103_20181210
      - mouse_763236014_20181210
      - mouse_763808604_20190108
      - mouse_769319624_20190108
      - mouse_774672366_20190119
      - mouse_791857608_20190201
      - mouse_800249587_20190208
      - mouse_795770036_20190208
      - mouse_800250057_20190214
      - mouse_811322619_20190305
      - mouse_803390291_20190306
      - mouse_813701562_20190311
      - mouse_817060751_20190319
      - mouse_821469666_20190321
      - mouse_827809884_20190408
  config:
    multitask_readout:
      - decoder_id: GABOR_POS_2D
        normalize_mean:
          - 4.00198751
          - 3.99451069
        normalize_std:
          - 2.58303208
          - 2.57868835
        metrics:
          - metric: r2
      - decoder_id: GABOR_ORIENTATION
        metrics:
          - metric: accuracy
      - decoder_id: DRIFTING_GRATINGS
        metrics:
          - metric: accuracy
      - decoder_id: DRIFTING_GRATINGS_TEMP_FREQ
        metrics:
          - metric: accuracy
      - decoder_id: RUNNING_SPEED
        normalize_mean: 10.97099596
        normalize_std: 19.75150106
        metrics:
          - metric: r2
      - decoder_id: GAZE_POS_2D
        normalize_mean:
          - 4.89581651
          - -1.97602398
        normalize_std:
          - 1.26124560
          - 1.19413048
        metrics:
          - metric: r2
      - decoder_id: PUPIL_SIZE_2D
        normalize_mean:
          - 43.09496815
          - 46.94002598
        normalize_std:
          - 13.91880302
          - 15.23047149
        metrics:
          - metric: r2


# only ('drifting_gratings', 'gabors', 'velocity')
- selection:
    - dandiset: "allen_visual_behavior_neuropixels"
      sortsets:
      - mouse_754477358_20181105
      - mouse_820866121_20190321
  config:
    multitask_readout:
      - decoder_id: GABOR_ORIENTATION
        metrics:
          - metric: accuracy
      - decoder_id: GABOR_POS_2D
        normalize_mean:
          - 4.00198751
          - 3.99451069
        normalize_std:
          - 2.58303208
          - 2.57868835
        metrics:
          - metric: r2
      - decoder_id: DRIFTING_GRATINGS
        metrics:
          - metric: accuracy
      - decoder_id: DRIFTING_GRATINGS_TEMP_FREQ
        metrics:
          - metric: accuracy
      - decoder_id: RUNNING_SPEED
        normalize_mean: 10.97099596
        normalize_std: 19.75150106
        metrics:
          - metric: r2