# these sessions have all
- selection:
    - dandiset: "allen_visual_behavior_neuropixels"
  config:
    sampling_intervals_modifier: |
      sampling_intervals = sampling_intervals & data.drifting_gratings
    multitask_readout:
      - decoder_id: DRIFTING_GRATINGS
        metrics:
          - metric: accuracy
      - decoder_id: DRIFTING_GRATINGS_TEMP_FREQ
        metrics:
          - metric: accuracy
