DATASET = "willett_henderson_speech_2023"

# use one file to check if data is downloaded
REMOTE_URL = "https://datadryad.org/stash/downloads/file_stream/2547369"

RAW_DIR = config["RAW_DIR"]
PROCESSED_DIR = config["PROCESSED_DIR"]

rule all:
    input:
        description = f"{PROCESSED_DIR}/{DATASET}/description.mpk"

rule download_data:
    output:
        tar_file = f"{RAW_DIR}/{DATASET}/competitionData.tar.gz"
    shell:
        f"""
        mkdir -p {RAW_DIR}/{DATASET}
        echo {RAW_DIR}/{DATASET}
        wget -O {RAW_DIR}/{DATASET}/competitionData.tar.gz {REMOTE_URL}
        """

rule untar:
    input:
        tar_file = f"{RAW_DIR}/{DATASET}/competitionData.tar.gz"
    output:
        mat_file = f"{RAW_DIR}/{DATASET}/competitionData/train/t12.2022.05.05.mat"
    shell:
        f"""
        tar -xvzf {RAW_DIR}/{DATASET}/competitionData.tar.gz -C {RAW_DIR}/{DATASET}
        """

rule prepare_data:
    input:
        py_script = f"data/scripts/{DATASET}/prepare_data.py",
        mat_file = f"{RAW_DIR}/{DATASET}/competitionData/train/t12.2022.05.05.mat"
    output:
        description = f"{PROCESSED_DIR}/{DATASET}/description.mpk"
    log:
        f".snakemake/logs/{DATASET}/prepare_data.log"
    shell:
        f"""
        mkdir -p {PROCESSED_DIR}/{DATASET}
        python data/scripts/{DATASET}/prepare_data.py --input_dir {RAW_DIR}/{DATASET}/competitionData/ --output_dir {PROCESSED_DIR}/{DATASET}
        """

include: "../freeze.smk"
