######################################################
# Flint & Slutzky (2012)
######################################################

DATASET = "flint_slutzky_accurate_2012"

RAW_DIR = config["RAW_DIR"]
PROCESSED_DIR = config["PROCESSED_DIR"]
COMPRESSED_DIR = config["COMPRESSED_DIR"]

DATASETS = [
    "e1", "e2", "e3", "e4", "e5"
]

rule all:
    input:
        f"{PROCESSED_DIR}/{DATASET}/description.mpk"
        # mat_files = expand(f"{RAW_DIR}/{DATASET}/Flint_2012_{{dataset}}.mat", dataset=DATASETS)

rule download_dataset:
    output:
        mat_file = f"{RAW_DIR}/{DATASET}/Flint_2012_{{dataset}}.mat"
    shell:
        f"""
        mkdir -p {RAW_DIR}/{DATASET}
        wget -O {RAW_DIR}/{DATASET}/Flint_2012_{{wildcards.dataset}}.mat "https://portal.nersc.gov/project/crcns/download/dream/data_sets/Flint_2012?fn=dream%2Fdata_sets%2FFlint_2012%2FFlint_2012_{{wildcards.dataset}}.mat&username=&password=&guest=1&fn=dream%2Fdata_sets%2FFlint_2012%2FFlint_2012_{{wildcards.dataset}}.mat&agree_terms=on&submit=Login+Anonymously"
        """

rule prepare_data:
    input:
        py_script = f"data/scripts/{DATASET}/prepare_data.py",
        mat_files = expand(f"{RAW_DIR}/{DATASET}/Flint_2012_{{dataset}}.mat", dataset=DATASETS),
        # nwb_files = expand(f"{RAW_DIR}/{DATASET}/broadband/{{dataset}}.nwb", dataset=BROADBAND_DATASETS)
    output:
        description = f"{PROCESSED_DIR}/{DATASET}/description.mpk"
    shell:
        f"""
        mkdir -p {PROCESSED_DIR}/{DATASET}
        python data/scripts/{DATASET}/prepare_data.py --input_dir {RAW_DIR}/{DATASET} --output_dir {PROCESSED_DIR}/{DATASET}
        """

include: "../freeze.smk"